version: 2
jobs:
  build_php_7_1:
    docker:
    - image: docker:stable
    steps:
    - checkout
    - setup_remote_docker
    - run:
        command: |
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          export PHP_BUILD=7.1
          if docker pull jakubkulhan/php:$PHP_BUILD &> /dev/null; then
            export CURRENT_VERSION=$(docker run --rm jakubkulhan/php:$PHP_BUILD -r 'echo PHP_VERSION;')
          else
            export CURRENT_VERSION=none
          fi
          docker build --pull --no-cache -t jakubkulhan/php:build php/$PHP_BUILD
          export NEW_VERSION=$(docker run --rm jakubkulhan/php:build -r 'echo PHP_VERSION;')
          # Only push if not already built
          if [ "$NEW_VERSION" == "$CURRENT_VERSION" ]; then
            echo "Already built: $NEW_VERSION"
          else
            # release
            export NEW_RELEASE_VERSION="$(docker run --rm jakubkulhan/php:build -r 'printf("%d.%d.%d", PHP_MAJOR_VERSION, PHP_MINOR_VERSION, PHP_RELEASE_VERSION);')"
            docker tag jakubkulhan/php:build "jakubkulhan/php:$NEW_RELEASE_VERSION"
            docker push "jakubkulhan/php:$NEW_RELEASE_VERSION"
            # minor
            export NEW_MINOR_VERSION="$(docker run --rm jakubkulhan/php:build -r 'printf("%d.%d", PHP_MAJOR_VERSION, PHP_MINOR_VERSION);')"
            docker tag jakubkulhan/php:build "jakubkulhan/php:$NEW_MINOR_VERSION"
            docker push "jakubkulhan/php:$NEW_MINOR_VERSION"
          fi

workflows:
  version: 2
  docker:
    jobs:
    - build_php_7_1
